base_url = "https://mintsuku.pages.dev"
title = "doom"
description = "Programmer with who can't stop picking new hobbies.."
compile_sass = false
minify_html = true
generate_feeds = true
default_language = "en"

taxonomies = [
    {name = "tags", feed = true},
]

[languages.fr]
generate_feeds = true
build_search_index = true

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "mintsuku"
display_author = true

favicon = "favicon.ico"
image = ""

default_theme = "light"
list_pages = false
twitter_card = true

header_nav = [
  { url = "/", name_en = "/home/", name_fr = "/accueil/" },
  { url = "/about", name_en = "/about/", name_fr = "/concernant/" },
  { url = "/journal", name_en = "/journal/", name_fr = "/journal/" },
  { url = "/blog", name_en = "/blog/", name_fr = "/blog/" }
]

# Optional footer license text. It will only show, when using footer_content_license.
#footer_content_license = "Creative Commons Attribution 4.0 International"
#footer_content_license_link = "https://creativecommons.org/licenses/by/4.0/"
